from typing import Any, Protocol

import polars as pl


class Backend(Protocol):
    def query(self, sql: str, params: Any = None) -> pl.DataFrame: ...
    def execute(self, sql: str, params: Any = None) -> int: ...
    def init_schema(self) -> None: ...
    def table_exists(self, name: str) -> bool: ...
